sudo: required
dist: trusty

language: 
node_js:
  - "5"
  
before_script:
  - sudo apt-get install ruby2.0
  - npm install gulpjs/gulp-cli#4.0 -g
  - npm install gulp -g
  - npm install 
  - bundle install --path vendor/bundle
script: gulp build --prod


