language: node_js, ruby
sudo: false
node_js:
- "5"
rvm:
- "2.1"
  
before_script:
  - npm install gulpjs/gulp-cli#4.0 -g
  - npm install --save-dev babel-core
  - npm install 
  - bundle install --path vendor/bundle
script: gulp build
